name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, sqlite

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build
        
      - name: Debug build output
        run: |
          echo "===== LIST public/build ====="
          ls -lah public/build || echo "❌ Build folder not found!"
          echo "===== LIST public/build/.vite ====="
          ls -lah public/build/.vite || true
          echo "===== MANIFEST ====="
          cat public/build/manifest.json || echo "❌ manifest.json not found!"

      - name: Ensure manifest exists
        run: |
          ls -lah public/build || echo "❌ Build folder not found!"
          test -f public/build/manifest.json || (echo "❌ manifest.json not found!" && exit 1)

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
